### ISSUE TITLE
Error in phonegap build

### ISSUE THREAD

**Issue by Ava-UwU** [arcadesindo/Construct2-Updated-Google-Play#1]
Hi. So the problem is I'm getting errors while exporting my project using phonegap, this is my log from phonegap.

[phonegap.txt](https://github.com/arcadesindo/Construct2-Updated-Google-Play/files/4764821/phonegap.txt)

and this is my config.xml:

	<icon src="www/icon-256.png" width="256" height="256" density="xxxhdpi" />
	<icon src="www/icon-128.png" width="128" height="128" density="xhdpi" />

	<preference name="android-targetSdkVersion" value="28" />

	<preference name="orientation" value="portrait" />
	<preference name="fullscreen" value="true" />
	<preference name="DisallowOverscroll" value="true" />
	<preference name="AllowInlineMediaPlayback" value="true" />

	<config-file parent="UIStatusBarHidden" platform="ios" target="*-Info.plist"><true/></config-file>
	<config-file parent="UIViewControllerBasedStatusBarAppearance" platform="ios" target="*-Info.plist"><false/></config-file>

	<preference name="deployment-target" value="10.0" />
	<preference name="android-minSdkVersion" value="21" />
	<access origin="*" />

	<plugin name="construct-play-games">
        <variable name="APP_ID" value="my app id" />
        </plugin>
	<plugin name="cordova-custom-config" />
	<plugin name="cordova-plugin-file" />
	<plugin name="cordova-plugin-inappbrowser" />
	<plugin name="cordova-plugin-statusbar" />
	<plugin name="cordova-plugin-whitelist" />
	<plugin name="cordova-plugin-wkwebview-engine" />

	<engine name="ios" />
	<engine name="android" />
</widget>

**Comment by Ava-UwU** [comment]
Ok I managed to get an apk with android studio, now the problem is it won't sign in. Google play games pops up and starts to connect and it shows a loading circle but the it disappears and nothing happens basically.

**Comment by arcadesindo** [comment]
Hello, for the phonegap issue, have you tried to add this line? I think it was happening because the default phonegap version did not support it.
<preference name="phonegap-version" value="cli-9.0.0" />

and for the Google play games issues, have you publish your game service yet? at least you need to release your game service to test mode.

**Comment by Ava-UwU** [comment]
Thank you for your answer.
About your first question, sorry I didn't understand, what "line" do you mean? I only added this (plugin name="construct-play-games"
    variable name="APP_ID" value="my app id" /
    /plugin) to my config.xml, as I copy pasted file itself in the first post.
And about the second question, I did publish my game service, but I noticed I did not publish the game itself, so I created a closed alpha track and I'm still waiting for invitation and links to be sent to testers. 
I'd like to mention that I only added my application ID to the plugin, in the engine. I didn't add client ID and secret ID, are they necessary?

**Comment by Ava-UwU** [comment]
Hello?!
